name: Build
on:
  push:
    branches:
      - master
      - gh-actions
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.github/**'
      - '!.github/workflows/build.yml'

jobs:
  macos-build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Disable License Manager
        run: find ./Configurations/Build -type f -name '*.xcconfig' -exec sed -i '' s/TEXTUAL_BUILT_WITH_LICENSE_MANAGER=1/TEXTUAL_BUILT_WITH_LICENSE_MANAGER=0/g {} +

      - name: Empty Code Signing Identity file
        run: echo "" > "Configurations/Build/Code Signing Identity.xcconfig"

      - name: Build the 'Standard Release' scheme
        run: xcodebuild -scheme "Textual (Standard Release)" build

      - name: Upload the built app
        uses: actions/upload-artifact@v3
        with:
          name: textual-standard-release
          path: Build\ Results/Release/Textual.app
